---

- name: Setup yuicompressor path
  file: path={{ yuicompressor_path }} state=directory

- name: Download yuicompressor
  get_url:
    url=https://github.com/yui/yuicompressor/releases/download/v{{ yuicompressor_version }}/yuicompressor-{{ yuicompressor_version }}.jar
    dest={{ yuicompressor_path }}/yuicompressor-{{ yuicompressor_version }}.jar
